# Generated by Django 4.2.5 on 2023-10-05 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('craeted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, max_length=50)),
                ('img', models.ImageField(upload_to='notes-img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
