# Generated by Django 4.2.5 on 2023-09-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
